#+TITLE: config-files
* Dot Files
To use the dot files in the root directory of the repo sym link them
to your home directory

* Emacs config
Emacs now uses use-package in an org mode file for its [[file:.emacs.d/config.org][configuration]].
This makes it easy to understand the configuration because notes can
easily be embedded explaining the configuration.

To use the config simply link to the ~.emacs.d~ directory and emacs
will fully configure itself on launch

* Bin Directory
You need to ensure the bin directory is in your path

** Bin Directory Scripts

*** Prompt
Usage:-

#+BEGIN_SRC bash
source prompt [default|git]
#+END_SRC

Sets the prompt to be customised to your environment

* Doc Directory
This directory contains useful information on applications that have
a dotfile in this repo.

As such it acts as a useful documentation resource for those applications
when cloning the repository. 

* Attribution
It is impossible to fully acknowledge or attribute all sources of
inspiration for the config files. Wwhere possible significant sources
are listed in the [[file:attribution.org][attribution]] file.
