#+TITLE: config-files
* Dot Files
  To use the dot files in the root directory of the repo sym link them
  to your home directory

  The .emacs.vanilla.d directory should not be linked to .emacs.d in the home
  directory. The .emacs.d has been reserved for if you want to use spacemacs.
  Because of this .emacs.vanilla.d expects to be linked to the same name in the
  home directory and the config file is setup to use .emacs.vanilla.d as its
  config directory. Not using this directory name will cause issues when
  launching with this configuration.

  In order to use the vanilla configuration set up an alias in your ~/.profile~
  or similar pointing to the config file and ignoring any others.

  #+BEGIN_SRC sh
  alias vemacs="/path/to/my/emacs -q -l ~/.emacs.vanilla.d/init.el"
  #+END_SRC

** Xresources
The Xresource file sets up configuration of clients to the X Windows
system. Client are any program rendered on the X Server. This means
things such as xterm configuration can be set here.

The Xresource file is read when the user logs in. If you need to
update changes made to the file while already logged in use ~xrdb~.

*** MAC's and X
If you want to be able to use programs that require an XServer on the
mac then you will need to install an XServer. XQuartz is an opensource
implemenation for the mac that was included in 10.5 through 10.7. The
web page for the software can be found at [[https://www.xquartz.org/][xquartx.org]].

#+BEGIN_SRC
xrdb ~/.Xresources
#+END_SRC

* Emacs config
Emacs now uses use-package in an org mode file for its [[file:.emacs.d/config.org][configuration]].
This makes it easy to understand the configuration because notes can
easily be embedded explaining the configuration.

To use the config simply link to the ~.emacs.d~ directory and emacs
will fully configure itself on launch

* Git Directory

There is a git directory setup to control or document git related
features such as global ignore files or global hooks. See the
documentation on the [[file:git/README.org][README]].

* Bin Directory
You need to ensure the bin directory is in your path

** Bin Directory Scripts

*** Prompt
Usage:-

#+BEGIN_SRC bash
source prompt [default|git]
#+END_SRC

Sets the prompt to be customised to your environment

* Doc Directory
This directory contains useful information on applications that have
a dotfile in this repo.

As such it acts as a useful documentation resource for those applications
when cloning the repository. 

* Attribution
It is impossible to fully acknowledge or attribute all sources of
inspiration for the config files. Wwhere possible significant sources
are listed in the [[file:attribution.org][attribution]] file.
